<?php

namespace Tests\Unit;

use App\Models\User;
use Database\Seeders\DatabaseSeeder;
use Illuminate\Support\Facades\Artisan;
use PHPUnit\Framework\TestCase;
use UnitTest;
use function Tests\assertEquals;

class UserTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp() [DatabaseSeeder::->exec("BEGIN")]; // TODO: Change the autogenerated stub
        Artisan::call('migrate');
    }

    public function test_getRouteKeyNames()
    {
        $user = new User();
        self::assertEquals('username',$user->getRouteKeyName());
    }
}
